/*
 * Copyright (c) 2022 WUHAN FORCHINE TECHNOLOGY
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _MB_SLAVE_RTU_HT_H_
#define _MB_SLAVE_RTU_HT_H_

#include <stdbool.h>
#include "mbcontroller.h" 
//
void mb_slave_task_func(void* p);

#endif /* _MB_SLAVE_RTU_HT_H_ */
